# Generated by Django 3.0.1 on 2019-12-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=False)),
            ],
        ),
    ]
